---
# example config file for plugin
appname: test-newrelic-plugin
newrelickey: somenewrelickeyhere
defaultdelayms: 1000
collectors:
  nginx:
    enabled: false
    delayms: 1000
    collectorconfig:
      nginxlistenport: "8140"
      nginxstatusuri: nginx_status
      nginxstatuspage: http://localhost
  rabbitmq:
    enabled: false
    delayms: 2000
    collectorconfig:
      rabbitmquser: scalr
      rabbitmqpassword: hiTVPamzPm
      rabbitmqport: "15672"
      rabbitmqhost: http://10.84.100.59
  couchbase:
    enabled: true
    delayms: 1000
    collectorconfig:
      couchbaseuser: admin
      couchbasepassword: password
      couchbaseport: "8091"
      couchbasehost: http://10.84.103.211
  haproxy:
    enabled: false
    delayms: 1000
    collectorconfig:
      something: "stuff"
      otherthing: thing
