---
# example config file for plugin
appname: test-newrelic-plugin
newrelickey: somenewrelickeyhere
defaultdelayms: 1000
tags:
  keyvalue:
    tag1: sometagvalue
    tag2: someothertagvalue
  env:
    - VAR_1
    - VAR_2
collectors:
  nginx:
    enabled: false
    delayms: 1000
    collectorconfig:
      nginxlistenport: "8140"
      nginxstatusuri: nginx_status
      nginxstatuspage: http://localhost
  rabbitmq:
    enabled: false
    delayms: 2000
    collectorconfig:
      rabbitmquser: scalr
      rabbitmqpassword: hiTVPamzPm
      rabbitmqport: "15672"
      rabbitmqhost: http://10.84.100.59
  couchbase:
    enabled: true
    delayms: 1000
    collectorconfig:
      couchbaseuser: admin
      couchbasepassword: password
      couchbaseport: "8091"
      couchbasehost: http://10.84.103.211
  haproxy:
    enabled: false
    delayms: 1000
    tags:
      keyvalue:
        tag3: sometagvalue3
        tag4: someothertagvalue4
      env:
        - VAR_3
        - VAR_4
    collectorconfig:
      something: "stuff"
      otherthing: thing
