---
# example config file for plugin
appname: test-newrelic-plugin
newrelickey: somenewrelickeyhere
defaultdelayms: 1000
collectors:
  nginx:
    enabled: true
    delayms: 1000
    collectorconfig:
      nginxlistenport: "8140"
      nginxstatusuri: nginx_status
      nginxstatuspage: http://localhost
  haproxy:
    enabled: true
    delayms: 1000
    collectorconfig:
      something: "stuff"
      otherthing: thing
